name: decast
description: A beautiful weather app with forecast
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP requests
  http: ^1.1.0

  # Environment variables (.env)
  flutter_dotenv: ^5.1.0

  # Location services
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

  # Date & time formatting
  intl: ^0.19.0

  # State management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # App icon generator
  flutter_launcher_icons: ^0.13.1

  # Recommended lint rules
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env

# Launcher icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
